package SoseLan21.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BolleanType = 0;
  public static final int ILangContent = 1;
  public static final int IStatement = 2;
  public static final int IntegerType = 3;
  public static final int SoSeWorksheet = 4;
  public static final int Type = 5;
  public static final int Variable = 6;
  public static final int VariableDeclaration = 7;
  public static final int VariableReference = 8;
  public static final int semicolon = 9;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x49e25ac895434e93L, 0xad91f1c8e0f96a25L);
    builder.put(0x7a4fffd757936caaL, BolleanType);
    builder.put(0x7a4fffd757936cabL, ILangContent);
    builder.put(0x7a4fffd75793e861L, IStatement);
    builder.put(0x7a4fffd757936cb1L, IntegerType);
    builder.put(0x7a4fffd757936ca7L, SoSeWorksheet);
    builder.put(0x7a4fffd75793e85cL, Type);
    builder.put(0x7a4fffd757936cb2L, Variable);
    builder.put(0x7a4fffd757936fe1L, VariableDeclaration);
    builder.put(0x7a4fffd757936fe2L, VariableReference);
    builder.put(0x4dbab519a5f536c7L, semicolon);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
