package SoseLan21.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class SoSeWorksheet_Constraints extends BaseConstraintsDescriptor {
  public SoSeWorksheet_Constraints() {
    super(CONCEPTS.SoSeWorksheet$xH);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept SoSeWorksheet$xH = MetaAdapterFactory.getConcept(0x49e25ac895434e93L, 0xad91f1c8e0f96a25L, 0x7a4fffd757936ca7L, "SoseLan21.structure.SoSeWorksheet");
  }
}
