package SoseLan21.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new BolleanType_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new IntegerType_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new SoSeWorksheet_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Variable_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new VariableDeclaration_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new VariableReference_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new semicolon_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x49e25ac895434e93L, 0xad91f1c8e0f96a25L, 0x7a4fffd757936caaL), MetaIdFactory.conceptId(0x49e25ac895434e93L, 0xad91f1c8e0f96a25L, 0x7a4fffd757936cb1L), MetaIdFactory.conceptId(0x49e25ac895434e93L, 0xad91f1c8e0f96a25L, 0x7a4fffd757936ca7L), MetaIdFactory.conceptId(0x49e25ac895434e93L, 0xad91f1c8e0f96a25L, 0x7a4fffd757936cb2L), MetaIdFactory.conceptId(0x49e25ac895434e93L, 0xad91f1c8e0f96a25L, 0x7a4fffd757936fe1L), MetaIdFactory.conceptId(0x49e25ac895434e93L, 0xad91f1c8e0f96a25L, 0x7a4fffd757936fe2L), MetaIdFactory.conceptId(0x49e25ac895434e93L, 0xad91f1c8e0f96a25L, 0x4dbab519a5f536c7L)).seal();
}
